version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: quarkus-user
      MINIO_ROOT_PASSWORD: quarkus-password
    ports:
      - "9000:9000"
      - "9001:9001"
